(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const ui = Object.fromEntries(['file-title','save-state','file-input','open-button','empty-open-button','template-button','empty-template-button','export-button','undo-button','redo-button','reset-button','portable-button','clear-draft-button','find-button','add-note-button','edit-toggle','script-toggle','preview-frame','empty-state','canvas-shell','frame-wrap','frame-label','canvas-zone','source-editor','notes-view','notes-list','note-count','inspector','inspector-empty','element-name','element-selector','attribute-editor','floating-toolbar','selection-color','zoom-input','zoom-output','find-dialog','find-input','replace-input','find-result','note-dialog','note-input','priority-input','toast','draft-copy'].map((id) => [id, $(id)]));
  const state = { original: '', html: '', filename: '', doctype: '<!doctype html>', history: [], future: [], selected: null, doc: null, notes: [], mode: 'design', editing: null, pendingEdit: false, dirty: false, viewport: 'fluid', zoom: 100 };
  const template = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>登录流程验收页</title><style>body{font-family:Arial,sans-serif;margin:0;background:#f7fafc;color:#19233c}.hero{padding:54px 8%;background:#16324f;color:white}.hero p{color:#c5f0e9}.card{max-width:760px;margin:34px auto;padding:28px;background:white;border:1px solid #d9e1ec;border-radius:14px;box-shadow:0 8px 24px #17203312}.row{display:flex;gap:14px;flex-wrap:wrap}.item{flex:1;min-width:150px;padding:16px;background:#eef8f7;border-radius:8px}.button{display:inline-block;padding:11px 17px;background:#0b7285;color:white;border-radius:6px;text-decoration:none}@media(max-width:600px){.hero{padding:36px 7%}}</style></head><body><header class="hero"><h1>登录流程验收页</h1><p>本页用于记录版本验收信息与风险项。</p><a class="button" href="#checklist">查看检查项</a></header><main class="card"><h2 id="checklist">本轮检查项</h2><div class="row"><section class="item"><strong>账户登录</strong><p>覆盖正确密码、错误密码和锁定账户。</p></section><section class="item"><strong>验证码</strong><p>确认超时、刷新及校验提示。</p></section><section class="item"><strong>移动端</strong><p>检查 390px 视口下的输入与按钮。</p></section></div><h2>验收结论</h2><p>请在此替换成实际版本的验收摘要。</p></main></body></html>`;

  function toast(message) { ui.toast.textContent = message; ui.toast.classList.add('visible'); clearTimeout(toast.timer); toast.timer = setTimeout(() => ui.toast.classList.remove('visible'), 2400); }
  function safeKey() { return `pagelab:draft:${state.filename || 'untitled'}`; }
  function setStatus(message) { ui['save-state'].textContent = message; }
  function setDirty(value) { state.dirty = value; setStatus(value ? '本地草稿已更新' : '与源版本一致'); }
  function serialize() { if (!state.doc) return state.html; return `${state.doctype}\n${state.doc.documentElement.outerHTML.replace(/ contenteditable="true"/g, '').replace(/ spellcheck="false"/g, '')}`; }
  function saveDraft() { if (!state.html) return; try { localStorage.setItem(safeKey(), JSON.stringify({ html: state.html, original: state.original, notes: state.notes, time: Date.now() })); ui['clear-draft-button'].disabled = false; ui['draft-copy'].textContent = '草稿已保存在当前浏览器。关闭后再次打开同名文件可恢复。'; } catch { ui['draft-copy'].textContent = '浏览器未允许保存本地草稿。'; } }
  function commit(message = '已更新') { state.html = serialize(); setDirty(state.html !== state.original); saveDraft(); updateActions(); if (message) toast(message); }
  function snapshot() { const current = serialize(); if (state.history.at(-1) === current) return; state.history.push(current); if (state.history.length > 40) state.history.shift(); state.future = []; updateActions(); }
  function updateActions() { const active = Boolean(state.html); ui['export-button'].disabled = !active; ui['undo-button'].disabled = !state.history.length; ui['redo-button'].disabled = !state.future.length; ui['edit-toggle'].disabled = !active || ui['script-toggle'].checked; ui['script-toggle'].disabled = !active; ui['clear-draft-button'].disabled = !active; }
  function restoreHtml(html, message) { state.html = html; render(); setDirty(state.html !== state.original); saveDraft(); if (message) toast(message); }
  function undo() { if (!state.history.length) return; state.future.push(serialize()); restoreHtml(state.history.pop(), '已撤销'); updateActions(); }
  function redo() { if (!state.future.length) return; state.history.push(serialize()); restoreHtml(state.future.pop(), '已重做'); updateActions(); }

  function activate(html, filename, original = html, notes = []) {
    const match = html.match(/^\s*(<!doctype[^>]*>)/i); state.doctype = match ? match[1] : '<!doctype html>';
    state.original = original; state.html = html; state.filename = filename; state.notes = notes; state.history = []; state.future = []; state.selected = null;
    ui['file-title'].textContent = filename; ui['empty-state'].hidden = true; ui['canvas-shell'].hidden = false; ui['edit-toggle'].checked = true; ui['script-toggle'].checked = false;
    render(); setDirty(html !== original); updateNotes(); updateActions(); saveDraft();
  }
  function openFile(file) { if (!file || (!/\.html?$/i.test(file.name) && file.type !== 'text/html')) return toast('请选择 HTML 文件'); const reader = new FileReader(); reader.onload = () => { const original = String(reader.result); let saved; try { saved = JSON.parse(localStorage.getItem(`pagelab:draft:${file.name}`)); } catch { saved = null; } if (saved && saved.original === original && confirm(`检测到 ${file.name} 的本地草稿，是否恢复？`)) activate(saved.html, file.name, original, saved.notes || []); else activate(original, file.name, original); toast(`已载入 ${file.name}`); }; reader.readAsText(file); }
  function render() {
    clearSelection(); const runScripts = ui['script-toggle'].checked;
    ui['preview-frame'].setAttribute('sandbox', runScripts ? 'allow-same-origin allow-scripts' : 'allow-same-origin');
    ui['preview-frame'].srcdoc = state.html;
  }
  ui['preview-frame'].addEventListener('load', () => { state.doc = ui['preview-frame'].contentDocument; if (!state.doc) return; if (!ui['script-toggle'].checked) bindFrame(); applyViewport(); });
  function editable() { return state.doc && ui['edit-toggle'].checked && !ui['script-toggle'].checked && state.mode === 'design'; }
  function bindFrame() {
    const doc = state.doc;
    try { doc.execCommand('styleWithCSS', false, true); } catch { /* non-critical */ }
    doc.addEventListener('mouseover', (event) => { if (!editable()) return; const el = target(event.target); if (el && el !== state.selected && el !== state.editing) el.style.outline = '2px dashed #0b7285'; }, true);
    doc.addEventListener('mouseout', (event) => { const el = target(event.target); if (el && el !== state.selected && el !== state.editing) el.style.outline = ''; }, true);
    doc.addEventListener('click', (event) => { if (!editable()) return; event.preventDefault(); event.stopPropagation(); const el = target(event.target); if (!el) return clearSelection(); if (textElement(el)) beginEdit(el); else select(el); }, true);
    doc.addEventListener('input', () => { if (!state.editing) return; if (state.pendingEdit) { snapshot(); state.pendingEdit = false; } debounceCommit(); }, true);
    doc.addEventListener('paste', (event) => { if (!state.editing) return; event.preventDefault(); doc.execCommand('insertText', false, event.clipboardData.getData('text/plain')); }, true);
    doc.addEventListener('selectionchange', placeTextToolbar);
    doc.addEventListener('keydown', (event) => { if (event.key === 'Escape') clearSelection(); if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'z') { event.preventDefault(); undo(); } }, true);
  }
  function target(node) { if (!node || node.nodeType !== Node.ELEMENT_NODE || ['HTML', 'BODY', 'HEAD', 'SCRIPT', 'STYLE'].includes(node.tagName)) return null; return node; }
  function textElement(el) { return !['IMG','VIDEO','SVG','CANVAS','IFRAME','INPUT','SELECT','TEXTAREA'].includes(el.tagName) && [...el.childNodes].some((n) => n.nodeType === Node.TEXT_NODE && n.textContent.trim()); }
  function beginEdit(el) { if (state.editing === el) return; endEdit(); select(el); state.editing = el; state.pendingEdit = true; el.contentEditable = 'true'; el.spellcheck = false; el.focus(); toast('正在编辑文字'); }
  function endEdit() { if (!state.editing) return; state.editing.contentEditable = 'false'; state.editing.removeAttribute('spellcheck'); state.editing = null; ui['floating-toolbar'].hidden = true; commit('文字已保存'); }
  function select(el) { endEdit(); if (state.selected) state.selected.style.outline = ''; state.selected = el; el.style.outline = '2px solid #0b7285'; ui['inspector-empty'].hidden = true; ui.inspector.hidden = false; updateInspector(); }
  function clearSelection() { if (state.editing) endEdit(); if (state.selected) state.selected.style.outline = ''; state.selected = null; ui.inspector.hidden = true; ui['inspector-empty'].hidden = false; ui['floating-toolbar'].hidden = true; }
  function selectorFor(el) { if (el.id) return `#${CSS.escape(el.id)}`; const bits=[]; let node=el; while(node && node.nodeType === 1 && node.tagName !== 'BODY' && bits.length < 4) { let bit=node.tagName.toLowerCase(); if(node.classList.length) bit += `.${[...node.classList].slice(0,2).map(CSS.escape).join('.')}`; else { const siblings=[...node.parentElement.children].filter((x)=>x.tagName===node.tagName); if(siblings.length>1) bit += `:nth-of-type(${siblings.indexOf(node)+1})`; } bits.unshift(bit); node=node.parentElement; } return bits.join(' > '); }
  function updateInspector() { const el=state.selected; if (!el || !state.doc) return; const css=ui['preview-frame'].contentWindow.getComputedStyle(el); ui['element-name'].textContent = `<${el.tagName.toLowerCase()}>`; ui['element-selector'].textContent = selectorFor(el); ui['attribute-editor'].value = [...el.attributes].filter((a) => a.name !== 'style' && a.name !== 'contenteditable' && a.name !== 'spellcheck').map((a) => `${a.name}=${a.value}`).join('\n'); document.querySelectorAll('.style-input').forEach((input) => { const prop=input.dataset.style; const value=css[prop]; if(input.type === 'color') input.value = colorHex(value) || '#000000'; else input.value = Math.round(parseFloat(value) || 0); }); }
  function colorHex(value) { const bits = value && value.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/); return bits ? `#${bits.slice(1).map((x) => Number(x).toString(16).padStart(2, '0')).join('')}` : null; }
  function applyStyle(input) { const el=state.selected; if (!el) return; snapshot(); const property=input.dataset.style; el.style[property] = input.type === 'color' ? input.value : `${input.value || 0}px`; commit('样式已调整'); updateInspector(); }
  document.querySelectorAll('.style-input').forEach((input) => input.addEventListener('change', () => applyStyle(input)));
  document.querySelector('.quick-actions').addEventListener('click', (event) => { const action=event.target.dataset.action; const el=state.selected; if (!action || !el) return; snapshot(); if(action === 'duplicate') { const clone=el.cloneNode(true); clone.removeAttribute('contenteditable'); el.after(clone); select(clone); } if(action === 'move-up' && el.previousElementSibling) el.previousElementSibling.before(el); if(action === 'move-down' && el.nextElementSibling) el.nextElementSibling.after(el); if(action === 'delete') { if(!confirm('删除这个元素？')) { state.history.pop(); return; } el.remove(); clearSelection(); } commit(action === 'delete' ? '元素已删除' : '元素已更新'); });
  $('apply-attributes-button').addEventListener('click', () => { if(!state.selected) return; snapshot(); const el=state.selected; [...el.attributes].filter((a) => !['style','contenteditable','spellcheck'].includes(a.name)).forEach((a) => el.removeAttribute(a.name)); ui['attribute-editor'].value.split('\n').map((line)=>line.trim()).filter(Boolean).forEach((line)=>{ const index=line.indexOf('='); if(index > 0) el.setAttribute(line.slice(0,index).trim(), line.slice(index+1).trim()); }); commit('属性已应用'); updateInspector(); });
  $('copy-selector-button').addEventListener('click', async () => { if(!state.selected) return; try { await navigator.clipboard.writeText(selectorFor(state.selected)); toast('CSS 路径已复制'); } catch { toast('浏览器未允许复制'); } });
  function placeTextToolbar() { if(!state.editing || !state.doc) return; const selection=state.doc.getSelection(); if(!selection || selection.isCollapsed || !selection.rangeCount) return ui['floating-toolbar'].hidden=true; const rect=selection.getRangeAt(0).getBoundingClientRect(); const frame=ui['preview-frame'].getBoundingClientRect(); if(!rect.width && !rect.height) return; ui['floating-toolbar'].hidden=false; ui['floating-toolbar'].style.left=`${Math.max(8, frame.left+rect.left)}px`; ui['floating-toolbar'].style.top=`${Math.max(8, frame.top+rect.top-40)}px`; }
  ui['floating-toolbar'].addEventListener('mousedown', (event)=>event.preventDefault()); ui['floating-toolbar'].addEventListener('click',(event)=>{ const command=event.target.closest('button')?.dataset.command; if(!command || !state.doc) return; snapshot(); state.doc.execCommand(command); commit('文本格式已更新'); }); ui['selection-color'].addEventListener('input',(event)=>{ if(!state.doc) return; snapshot(); state.doc.execCommand('foreColor',false,event.target.value); commit('文字颜色已更新'); });
  let commitTimer; function debounceCommit() { clearTimeout(commitTimer); commitTimer=setTimeout(()=>commit('文字已保存'),350); }
  function applyViewport() { const width=state.viewport === 'fluid' ? '100%' : `${state.viewport}px`; ui['frame-wrap'].style.width=width; ui['frame-wrap'].style.transform=`scale(${state.zoom/100})`; ui['frame-wrap'].style.marginBottom=state.zoom < 100 ? '0' : `${Math.max(0,(state.zoom-100)*5)}px`; ui['frame-label'].textContent=state.viewport === 'fluid' ? '自适应预览' : `${state.viewport}px 预览`; }
  document.querySelectorAll('[data-viewport]').forEach((button)=>button.addEventListener('click',()=>{ state.viewport=button.dataset.viewport; document.querySelectorAll('[data-viewport]').forEach((item)=>item.classList.toggle('active',item===button)); applyViewport(); })); ui['zoom-input'].addEventListener('input',()=>{state.zoom=Number(ui['zoom-input'].value);ui['zoom-output'].value=`${state.zoom}%`;applyViewport();});
  function changeMode(mode) { state.mode=mode; endEdit(); document.querySelectorAll('.tab').forEach((tab)=>{const active=tab.dataset.mode===mode;tab.classList.toggle('active',active);tab.setAttribute('aria-selected',String(active));}); ui['canvas-shell'].hidden=mode!=='design'; ui['source-editor'].hidden=mode!=='source'; ui['notes-view'].hidden=mode!=='notes'; if(mode==='source') ui['source-editor'].value=serialize(); if(mode==='design') render(); }
  document.querySelectorAll('.tab').forEach((tab)=>tab.addEventListener('click',()=>changeMode(tab.dataset.mode))); ui['source-editor'].addEventListener('change',()=>{snapshot(); state.html=ui['source-editor'].value; setDirty(state.html!==state.original); saveDraft();toast('源码已保存，切回设计模式即可预览');});
  function updateNotes() { ui['note-count'].textContent=state.notes.length; if(!state.notes.length) {ui['notes-list'].innerHTML='<p class="muted">还没有批注。选中页面元素后，点击左边的“添加验收批注”。</p>';return;} ui['notes-list'].innerHTML=state.notes.map((note,index)=>`<article class="note-card ${note.priority}"><button class="note-delete" data-note-index="${index}">删除</button><div class="note-meta"><strong>${note.priority}</strong><span>${note.selector}</span><span>${new Date(note.time).toLocaleString()}</span></div><p>${escapeHtml(note.text)}</p></article>`).join(''); }
  function escapeHtml(value) { const div=document.createElement('div');div.textContent=value;return div.innerHTML; }
  ui['add-note-button'].addEventListener('click',()=>{if(!state.selected)return toast('请先在页面中选中一个元素');ui['note-input'].value='';ui['note-dialog'].showModal();}); $('save-note-button').addEventListener('click',(event)=>{const text=ui['note-input'].value.trim();if(!text){event.preventDefault();return toast('请填写问题描述');}state.notes.unshift({text,priority:ui['priority-input'].value,selector:selectorFor(state.selected),time:Date.now()});updateNotes();saveDraft();toast('批注已保存');}); ui['notes-list'].addEventListener('click',(event)=>{const index=event.target.dataset.noteIndex;if(index===undefined)return;state.notes.splice(Number(index),1);updateNotes();saveDraft();});
  ui['find-button'].addEventListener('click',()=>ui['find-dialog'].showModal()); $('find-next-button').addEventListener('click',()=>findNext()); $('replace-all-button').addEventListener('click',()=>replaceAll()); function findNext(){const q=ui['find-input'].value.trim();if(!q||!state.doc)return;const walker=state.doc.createTreeWalker(state.doc.body,NodeFilter.SHOW_TEXT);let found;while(walker.nextNode()){if(walker.currentNode.nodeValue.includes(q)){found=walker.currentNode;break;}}if(!found)return ui['find-result'].textContent='未找到匹配内容。';const el=found.parentElement;select(el);el.scrollIntoView({block:'center'});ui['find-result'].textContent='已在预览中定位第一处匹配。';} function replaceAll(){const q=ui['find-input'].value;if(!q||!state.doc)return;const replacement=ui['replace-input'].value;snapshot();let count=0;const walker=state.doc.createTreeWalker(state.doc.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach((node)=>{if(node.nodeValue.includes(q)){node.nodeValue=node.nodeValue.split(q).join(replacement);count++;}});commit(`已替换 ${count} 个文本节点`);ui['find-result'].textContent=`已替换 ${count} 个文本节点。`;}
  async function exportHtml(portable=false) { endEdit(); let output=serialize(); if(portable && state.doc) { const images=[...state.doc.images].filter((image)=>image.src && !image.src.startsWith('data:')); let done=0; for(const image of images){try{const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;canvas.getContext('2d').drawImage(image,0,0);image.src=canvas.toDataURL('image/png');done++;}catch{/* cross-origin image stays untouched */}} output=serialize(); if(done)toast(`已内嵌 ${done} 张图片`); } const blob=new Blob([output],{type:'text/html;charset=utf-8'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=(state.filename||'page').replace(/\.html?$/i,'')+(portable?'-portable':'-edited')+'.html';link.click();URL.revokeObjectURL(link.href);toast('页面已导出'); }
  ui['export-button'].addEventListener('click',()=>exportHtml()); ui['portable-button'].addEventListener('click',()=>exportHtml(true)); $('export-notes-button').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state.notes,null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=(state.filename||'page').replace(/\.html?$/i,'')+'-notes.json';link.click();URL.revokeObjectURL(link.href);toast('批注 JSON 已导出');});
  function reset(){if(!state.html||!confirm('回到刚打开时的版本？当前编辑将只保留在本地草稿中。'))return;state.history=[];state.future=[];state.notes=[];restoreHtml(state.original,'已回到源版本');updateNotes();} ui['reset-button'].addEventListener('click',reset); ui['clear-draft-button'].addEventListener('click',()=>{localStorage.removeItem(safeKey());ui['draft-copy'].textContent='当前草稿已清除。';toast('本地草稿已清除');});
  function openPicker(){ui['file-input'].click();} ui['open-button'].addEventListener('click',openPicker);ui['empty-open-button'].addEventListener('click',openPicker);ui['file-input'].addEventListener('change',()=>{openFile(ui['file-input'].files[0]);ui['file-input'].value='';}); function openTemplate(){activate(template,'qa-acceptance-template.html');toast('已打开验收模板');}ui['template-button'].addEventListener('click',openTemplate);ui['empty-template-button'].addEventListener('click',openTemplate); ui['canvas-zone'].addEventListener('dragover',(event)=>{event.preventDefault();ui['canvas-zone'].classList.add('dragging');});ui['canvas-zone'].addEventListener('dragleave',()=>ui['canvas-zone'].classList.remove('dragging'));ui['canvas-zone'].addEventListener('drop',(event)=>{event.preventDefault();ui['canvas-zone'].classList.remove('dragging');openFile(event.dataTransfer.files[0]);});
  ui['edit-toggle'].addEventListener('change',()=>{if(!ui['edit-toggle'].checked)clearSelection();toast(ui['edit-toggle'].checked?'已开启可视化编辑':'已切换为只读预览');});ui['script-toggle'].addEventListener('change',()=>{if(ui['script-toggle'].checked&&!confirm('运行脚本会执行该 HTML 中的 JavaScript。仅对可信文件继续。')){ui['script-toggle'].checked=false;return;}clearSelection();render();toast(ui['script-toggle'].checked?'已运行页面脚本，可视化编辑暂时关闭':'已切换到静态安全预览');});
  document.addEventListener('keydown',(event)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='s'){event.preventDefault();if(state.html)exportHtml();}if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='z'){event.preventDefault();undo();}if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='y'){event.preventDefault();redo();}if(event.key==='Escape')clearSelection();}); ui['undo-button'].addEventListener('click',undo);ui['redo-button'].addEventListener('click',redo);
  updateActions();
})();
